apiVersion: v1
kind: Template
metadata:
  name: config-map-template
  namespace: rates
objects:
  - kind: ConfigMap
    apiVersion: v1
    data:
    metadata:
      name: rates-config
  - kind: ConfigMap
    apiVersion: v1
    data:
      IATX_URL: "https://iatx-api-rates.apps.ocppaz1.ar.bsch/iatx-api"
      EXTERNALENTITY_WEBCLIENT_TIMEOUT: "3s"
      IATX_CICS: "FEINIP1"
      IATX_PORT: "2100"
      IATX_GATEWAY: "mvscpub.ar.bsch"
      ORA_CONN_STRING: "oraftdsrv01.iaas.ar.bsch:7365/srv_rio355_ap"
    metadata:
      name: externalentity-api-config-map
  #- apiVersion: v1
  #  kind: Secret
  #  metadata:
  #    name: oracle-rio355-password #ORA_FTD_PASS
  #  stringData:
  #    secret: "DUMMY_PASS"
  #  type: Opaque
  #- apiVersion: v1
  #  kind: Secret
  #  metadata:
  #    name: oracle-rio355-user #ORA_FTD_USER
  #  stringData:
  #    secret: "FTD_USER"
  #  type: Opaque
  #- apiVersion: v1
  #  kind: Secret
  #  metadata:
  #    name: iatx-password #IATX_PASS
  #  stringData:
  #    secret: "DUMMY_PASS"
  #  type: Opaque
  #- apiVersion: v1
  #  kind: Secret
  #  metadata:
  #    name: iatx-user #IATX_USER
  #  stringData:
  #    secret: "USRPBOP1"
  #  type: Opaque
  - apiVersion: v1
    kind: Secret
    metadata:
      name: myentity-local-ibm-client-id #MYENTITY_LOCAL_IBM_CLIENT_ID
    stringData:
      secret: "changeme"
    type: Opaque
  - apiVersion: v1
    kind: Secret
    metadata:
      name: externalentity-ibm-client-id #EXTERNALENTITY_LOCAL_IBM_CLIENT_ID
    stringData:
      secret: ""
    type: Opaque
